### ISSUE TITLE
Create Thumbnail

### ISSUE THREAD

**Issue by Fyb3roptik** [xfrr/goffmpeg#25]
Is there a way to also create a thumbnail? That would be awesome

**Comment by feelosophical88** [comment]
@Fyb3roptik Was there ever a solution for this?

**Comment by feelosophical88** [comment]
FWIW, I figured out a solution. I forked the repo, then added this block of code inside the `Initialize` function underneath the original `command` execution:
```go
outputFolder := outputPath[:strings.LastIndexByte(outputPath, '/')]
actionOutput := outputFolder + "/action-shot.jpg"
actionShotCommand := []string{"-ss", "60", "-i", inputPath, "-qscale:v", "4", "-frames:v", "1", actionOutput}
cmd2 := exec.Command(cfg.FfmpegBin, actionShotCommand...)
cmd2.Stdout = &out2
	
err2 = cmd2.Start()
if err2 != nil {
    return fmt.Errorf("error executing (%s) | error: %s", actionShotCommand, err2)
}
```

It works but I'm pretty new to Go so some of the code could be unnecessary. The caveat here is that I'm running this code every time a video is transcoded rather than creating a function to use it when I need it, but hopefully this gives someone a head-start.
